import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Router } from 'next/router'
import {useRouter} from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div><h1>Welcome to Next.js!</h1></div>
      <Link href="/posts/first">First Post</Link><br></br>
      <Link href="/posts/asdf">Dynamic </Link><br></br>
      <br></br>
      <img src="/favicon.ico" width={100} height={100}></img>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/posts/first")}>First</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/23/review/123")}>Review Page</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/getStaticpropsSSG")}>getStaticProps</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/blogs")}>getStaticPath</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/dashboard")}>Client Side Data Fetching</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/dashboard-swr")}>SWR for Client Side Data Fetching</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/events")}>Pre-rendering + Client Side Data Fetching</button>
      <br></br>
      <br></br>
      <button onClick={()=>router.push("/comments")}>API Routes</button>
    </div>
  )
}
